---

- name: Install And Configure Docker
  block:
    - name: Update Packages
      yum:
        name: "*"
        state: latest
        update_cache: true

    - name: Install Packages
      yum:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - docker
          - python
          - python-pip
          - python3
          - python3-pip

    - name: Install Python 2 Packages (needed by Ansible)
      pip:
        name: "{{ packages }}"
        extra_args: --ignore-installed
        state: present
      vars:
        packages:
          - docker~=4.4
          - jsondiff~=1.3

    - name: Install Python 3 Packages (needed by Ansible)
      pip:
        name: "{{ packages }}"
        executable: pip3
        extra_args: --ignore-installed
        state: present
      vars:
        packages:
          - docker~=5.0
          - docker-compose~=1.29.0
          - jsondiff~=1.3
          # Have to keep urllib3 v2.0 from being installed, which requires OpenSSL 1.1.1
          - urllib3~=1.26.15

    - name: Overwrite Docker Config File (sets ulimits)
      copy:
        src: docker
        dest: /etc/sysconfig/docker
        owner: root
        group: root
        mode: '0644'
        backup: yes
        follow: yes
      notify:
        - Restart Docker Service

    - name: Add User To Docker Group
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes

    - name: Ensure Docker Service Is Running
      service:
        name: docker
        state: started

    # Need to reset the connection so that group changes take effect
    - name: Reset SSH Connection
      meta: reset_connection

  become: true
