dnsproxy:
  image: defreitas/dns-proxy-server:latest
  container_name: dnsproxy
  labels:
    race.rib.deployment-name: ${{DEPLOYMENT_NAME}}
    race.rib.deployment-type: local
  networks:
    outside:
      ipv4_address: 10.11.0.250
  ports:
  - 5380:5380
  volumes:
    # - /etc/resolv.conf:/etc/resolv.conf
    - /var/run/docker.sock:/var/run/docker.sock
    - ${{HOST_RIB_STATE_PATH}}/deployments/local/${{DEPLOYMENT_NAME}}/dnsproxy/config.json:/app/conf/config.json 

openvpn:
  image: ixdotai/openvpn:0.2.3
  container_name: openvpn
  labels:
    race.rib.deployment-name: ${{DEPLOYMENT_NAME}}
    race.rib.deployment-type: local
  networks:
    outside:
      ipv4_address: 10.11.0.251
  volumes:
    - ${{HOST_RIB_STATE_PATH}}/deployments/local/${{DEPLOYMENT_NAME}}/vpn/config:/etc/openvpn 
    - /etc/resolv.conf:/etc/resolv.conf
  ports:
    - "1194:1194"
    - "1194:1194/udp"
  environment:
    - "DEBUG=1"
  cap_add:
    - NET_ADMIN
  sysctls:
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.default.forwarding=1
    - net.ipv6.conf.all.disable_ipv6=0
